### ISSUE TITLE
maize_genefunc.txt file

### ISSUE THREAD

**Issue by Bobo22331** [liusy-jz/MODAS#2]
Hi, 
In the demo data (https://github.com/liusy-jz/MODAS_data), I couldn't find the ann file `maize_genefunc.txt` needed by the last step. So, can you provide it? Thank you!

**Comment by liusy-jz** [comment]
Sorry, I forgot it. I have uploaded  **maize_genefunc.txt** file  to MODAS_data, you can download now.

**Comment by Hangtttt** [comment]
您好，我使用git lfs pull拉取文件后，发现文件没有改变。文件内容还是网址和大小。

**Comment by liusy-jz** [comment]
什么意思，是下载不了文件？

**Comment by Hangtttt** [comment]
是的，下来的文件夹内容是一个链接，表示数据是存在LFS




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年7月5日(星期六) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liusy-jz/MODAS] maize_genefunc.txt file (#2)












liusy-jz left a comment (liusy-jz/MODAS#2)
 
什么意思，是下载不了文件？
